# Generated by Django 5.1.1 on 2025-05-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_branch_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_contact_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
